# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: NAGPTooling
  #vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Connecting to Oracle database...
    
    set host=EPSILON-DB-TSTA.0487.P2.WU2.R53.CD2.BP.COM
    set port=1521
    set service=EPSCLDTSTA
    set user=SQL_RARG2S
    set password=L#Bgtw8WVHg8a6Z
    set query=SELECT * FROM CURVE_DEFINITIONS WHERE curve_num in (5813)
    
    REM Construct SQL*Plus command
    set sqlplusCommand=sqlplus %user%/%password%@//%host%:%port%/%service% @query.sql
    
    REM Create a temporary SQL file for the query
    echo %query% > query.sql
    
    REM Execute SQL*Plus command
    %sqlplusCommand%
    
    REM Delete temporary SQL file
    del query.sql

  displayName: 'Connect to Oracle Database'

  #env:
    #MYSQL_USERNAME: $(MYSQL_USERNAME)
    #MYSQL_PASSWORD: $(MYSQL_PASSWORD)
