# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: NAGPTooling
  #vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     cat readme.txt
#     num_characters=$(wc -c < readme.txt)
#     if [ "$num_characters" -lt 100 ]; then
#       echo "Number of characters is correct ($num_characters)."
#     else
#       echo "Number of characters is incorrect. Expected: 100, Actual: $num_characters"
#       exit 1  # Fail the pipeline if the count is incorrect
#     fi
#   displayName: 'Run a multi-line script'
  
# - script: |
#     echo "Connecting to MySQL database..."
#   displayName: 'Connect to MySQL Database'


- script: |
    echo "Connecting to Oracle database..."
# mysql -h EPSILON-DB-TSTA.0487.P2.WU2.R53.CD2.BP.COM -u SQL_RARG2S -p L#Bgtw8WVHg8a6Z -D EPSCLDTSTA -e "SELECT * FROM CURVE_DEFINITIONS WHERE curve_num in (5813)"
  displayName: 'Connect to Oracle Database'
  $host = "EPSILON-DB-TSTA.0487.P2.WU2.R53.CD2.BP.COM"
  $port = "1521"  # Default port for Oracle
  $service = "EPSCLDTSTA"
  $user = "SQL_RARG2S"
  $password = "L#Bgtw8WVHg8a6Z"
  $query = "SELECT * FROM CURVE_DEFINITIONS WHERE curve_num in (5813);"

# Construct SQL*Plus command
$sqlplusCommand = "sqlplus $user/$password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$host)(PORT=$port))(CONNECT_DATA=(SERVICE_NAME=$service))) <<EOF `"$query`"; exit; EOF"

# Execute SQL*Plus command
#Invoke-Expression -Command $sqlplusCommand
$output = Invoke-Expression -Command $sqlplusCommand

# Print the output
Write-Output $output
  #env:
    #MYSQL_USERNAME: $(MYSQL_USERNAME)
    #MYSQL_PASSWORD: $(MYSQL_PASSWORD)
